Error: git verion #3 (#6)
* setting for develop environment

* Develops HomePage outline

* Refactoring HomePage

* fixed untracked files

* Refactoring HomePage at new branch

* Tests and restructures for HomePage

* Error: Naver Cafe API / Stopgap: location.replace

* Error: This branch has conflicts that must be resolved

* Commits for setting git's version

* Resolving conflicts: index.jsx

* Resolving conflicts between origin and upstream

* Resolving conflicts between origin and upstream #2

* ERROR * : need to restore for package, package-lock, app, app.test, index, slice, testPage
  
Co-authored-by: iamhwang <iamhwang@iamhwangui-MacBookPro.local>